### ISSUE TITLE
Control buttons

### ISSUE THREAD

**Issue by stephini** [SonnyJim/snesbot#1]
Hi, I was wondering how difficult it would be to add some tact switches and maybe LEDs to control and readout the state of the SNESbot. I'd obviously want to do this without introducing undue lag. I am actually planning to use a B+2. I hope and assume the added power of the processor doesn't mess with SNESbot at all.

**Comment by SonnyJim** [comment]
I'm not 100% sure what you are asking?  Right now there's 3 ways you can provide output to the SNES:
1.  Using a real SNES controller wired up to the GPIO
2.  Using a USB joystick plugged into the Pi
3.  Recorded files generated by an emulator using the polldump scripts.

It would be possible to add some buttons via the spare GPIO, but I haven't written any code for that.

"I'd obviously want to do this without introducing undue lag."
You don't really get any lag, as there's plenty of time between the latch pulses to read the joysticks and load up the 4021's with data for the SNES to read out.

"I am actually planning to use a B+2"
Not a problem, I'm using one at the moment and it works fine.

I do need to update the schematic though, right now I don't think I completed the schematic for the v2 hardware.

**Comment by stephini** [comment]
I was actually asking about Record, Stop, Play buttons and readout LEDs.

Though it would also be cool to have LEDs read out what button is being pressed at any moment.

I can also see if there is enough spare GPIOs after the 3 buttons adding support for an LCD matrix, with this instead of having 3 lights (theoretically delineated by color) you could have the words Record, Standby and Play read out on the screen. I personally don't have an LCD matrix to use and LEDs would be cheaper to procure, I just think the idea sounds cool.

**Comment by SonnyJim** [comment]
Ah ok, I see what you are getting at.  Right now I just use ssh to control and monitor the bot, but what most of what you have mentioned I've thought about adding at some point.  This is all very low on my priorities atm, as a lot of it is 'window dressing'.

**Comment by stephini** [comment]
Yeah, I can definitely see where you are coming from on that. Has the bot been tested on Super Metroid at all? That's the game I'll be needing it for. Didn't see it on either list.

**Comment by SonnyJim** [comment]
I'm not 100% sure, personally I haven't tried it myself.  I do know that some of the guys at TASVideos.org have had problems with it, but they tend to focus on runs recorded in emulators which are then run on real hardware, rather than runs recorded on hardware and then played back.  It may be that Super Metroid does something that isn't emulated very well, so a real hardware recording may work.

Also bear in mind my current approach with the pair of 4021's isn't a great solution for a couple of reasons:
1.  It requires doubling a lot of the hardware for each player, currently each player output to the SNES will require 2 x 4021's and a MCP23017 to drive it.  Some of the runs rely on having 4 controllers/multitaps, which would end up being quite a lot of hardware
2.  It'll only ever 'work' with runs that treat the output to the SNES as a controller (ie 12 buttons).  There are a few TAS runs that don't work this way, rather they rely on a 'bit stream' being fed into the SNES.  These runs require something like an MCU or FPGA talking to the SNES.
3.  It requires more wiring than the MCU/FPGA approach, as you'll need to wire up quite a few connections per player, whereas the MCU/FPGA approach only requires a few wires to emulate a lot of controllers.

For what it is though, I think the design hits a happy balance between easy to build/cheap parts/easy to understand.  If you plan to build any hardware let me know and I'll get the schematics updated.

**Comment by stephini** [comment]
Yeah I actually already ordered the 4 chips. have 2 breadboards and a Tbreakout board and a bunch of proto wires. I also have some solid core in case i run out of proto wires. : P

I'm planning to play Super Metroid on my SFC using the SNESbot in record mode then put it in play mode on my SNES so I can show side by side the graphics issues I'm experiencing only on my SFC.

I had thought about looking up some speedruns but it seems like for Super Metroid zsnes and snex9x are ALL the vids. No one likes using byuu's. Guessing byuu's and real hardware break some of the glitches TASers rely on for Super Metroid.

**Comment by SonnyJim** [comment]
I've tried a few different emulators namely snes9x, lsnes and bizhawk.  I've only had good results from lsnes, mostly due to it's focus on emulation accuracy.  snes9x just desyncs on the first 'lag' frame and with bizhawk, well, I approached one of the authors with a few questions and got treated to a tirade of abuse which I won't repeat here, so I'm not really interested in using it at the moment, or at least until they get an attitude adjustment. 

You are right in saying that there isn't a lot of runs in lsnes format at the moment, hopefully this will be changing as I believe it's the preferred format for TASvideos submissions.  If you look here you'll find a list of just lsnes movies:
http://tasvideos.org/Movies-TypeL.html

You shouldn't have much trouble building the hardware, but there's a few gotchas that I hopefully pointed out in the readme:

One important thing to note is that the Pi GPIO _does not like_ being fed with 5V and I didn't get very good results using a voltage divider to step it down to 3.3v.  I'm currently using a SN74LVC245 running at 3.3v to step down the 5V latch line:
http://www.ti.com/product/sn74lvc245

I'd also recommend buying one of the shitty knockoff controllers off eBay for the controller connector, works out to be the cheapest way of acquiring them, either those or a controller extender cable you should be able to find for <$10.

EDIT: And btw, make sure you've got the right cable!  Jap Super Famicoms use an RGB cable that has capacitors rather than resistors!

**Comment by stephini** [comment]
Yeah it makes sense for HLE emulators to have syncing problems with real hardware. Thank goodness Byuu made an LLE emulator for SNES.

I hope you are right. However, I can see some speedrunners wanting to stick with HLE emulators since the imperfect emulation may give access to glitches not present in real hardware and LLEs.

Yeah. 3.3v vs 5v is a common problem for the Pi since so many logic circuits are built on 5v but the Pi crew decided to make the Pi 3.3v tolerant for whatever reason.

I actually have a plug off of a brand name SNES controller I got with my SNES that was unusably broken in the case. Still need to get some first party controllers of decent quality. Third party controllers SO don't work in metroid since none seem to have a mechanism to prevent dpad zeroing.
